### ISSUE TITLE
Add support for In Memory JDBC cache

### ISSUE THREAD

**Issue by emmanuel-keller** [qwazr/jdbc-cache-driver#18]
There are some use cases where we know we have enough memory
and we want to be as fast as possible so we just want to hold
in memory a ResultSet related to a given Statement.

This commit implements a new type of cache using memory
instead of hard disk files.

It uses a naive implementation with ByteArrayStreams which is not recommended for production.

```java
// Initialize the cache driver
Class.forName("com.qwazr.jdbc.cache.Driver");

// Provide the URL and the Class name of the backend driver
Properties info = new Properties();
info.setProperty("cache.driver.url", "jdbc:derby:memory:myDB;create=true");
info.setProperty("cache.driver.class", "org.apache.derby.jdbc.EmbeddedDriver");
// Get your JDBC connection
Connection cnx = DriverManager.getConnection("jdbc:cache:mem:my-memory-cache", info);
```

The syntax of the URL can be:

* *jdbc:cache:file:{path-to-the-cache-directory}* for on disk cache
* *jdbc:cache:mem:{name-of-the-cache}* for in memory cache

**Comment by emmanuel-keller** [comment]
@dadoonet Thanks for that great patch ! https://github.com/qwazr/jdbc-cache-driver/commit/8226a356c0c2a21fea457448b9b6434c9bafdce7

Do you have any idea of which improvement would make it production ready ? (having the next 1.3 release in mind)

Using a [MappedByteBuffer](https://docs.oracle.com/javase/7/docs/api/java/nio/MappedByteBuffer.html) for instance ?

**Comment by dadoonet** [comment]
Might be a good idea indeed. I took the most naive approach at the beginning but yeah that might work.
My goal with all that is to use your library with the on disk or in memory cache system within an elasticsearch plugin. So I need to check if it actually can run in the context of a java application with a security manager.

I'll give it a try.

Note that with the code we have now, we can always add a new implementation easily. In addition to `jdbc:cache:mem:my-memory-cache` we can add support for use `jdbc:cache:mmap:my-memory-cache`. WDYT?

**Comment by emmanuel-keller** [comment]
> we can add support for use jdbc:cache:mmap:my-memory-cache.

https://github.com/qwazr/jdbc-cache-driver/issues/21
